### ISSUE TITLE
Confusing Title Please swap

### ISSUE THREAD

**Issue by Arthur-Systems** [pixelizedgaming/PixelHardcore#3]
Please rename from PixleHarcore to HardcarePixle but replace the ixle with orn

**Comment by restics** [comment]
I have an issue with you existing

**Comment by restics** [comment]
L bozo get sent

**Comment by Arthur-Systems** [comment]
<h1>Crying</h1>
<p> Here is my sincere reaction</p>
<br>
<img src="https://i.etsystatic.com/21680765/r/il/4e3e0b/3272517351/il_1588xN.3272517351_2lee.jpg" alt="UCSC ITS Logo" width="100" height="100">
